[2025-06-11T12:13:34.280+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-11T12:13:34.309+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_ml_pipeline.setup_mlflow manual__2025-06-11T12:13:31.335012+00:00 [queued]>
[2025-06-11T12:13:34.320+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_ml_pipeline.setup_mlflow manual__2025-06-11T12:13:31.335012+00:00 [queued]>
[2025-06-11T12:13:34.320+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-06-11T12:13:34.337+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): setup_mlflow> on 2025-06-11 12:13:31.335012+00:00
[2025-06-11T12:13:34.357+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=858) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-11T12:13:34.359+0000] {standard_task_runner.py:72} INFO - Started process 867 to run task
[2025-06-11T12:13:34.360+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'nyc_taxi_ml_pipeline', 'setup_mlflow', 'manual__2025-06-11T12:13:31.335012+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_full.py', '--cfg-path', '/tmp/tmpwfwbe60h']
[2025-06-11T12:13:34.363+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask setup_mlflow
[2025-06-11T12:13:34.430+0000] {task_command.py:467} INFO - Running <TaskInstance: nyc_taxi_ml_pipeline.setup_mlflow manual__2025-06-11T12:13:31.335012+00:00 [running]> on host e64a68750d42
[2025-06-11T12:13:34.537+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ml-team' AIRFLOW_CTX_DAG_ID='nyc_taxi_ml_pipeline' AIRFLOW_CTX_TASK_ID='setup_mlflow' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T12:13:31.335012+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T12:13:31.335012+00:00'
[2025-06-11T12:13:34.538+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-11T12:13:34.826+0000] {logging_mixin.py:190} WARNING - 2025/06/11 12:13:34 INFO mlflow.tracking.fluent: Experiment with name 'nyc-taxi-experiment' does not exist. Creating a new experiment.
[2025-06-11T12:13:34.875+0000] {logging_mixin.py:190} INFO - MLflow setup completed
[2025-06-11T12:13:34.876+0000] {python.py:240} INFO - Done. Returned value was: MLflow configured
[2025-06-11T12:13:34.908+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-11T12:13:34.908+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=nyc_taxi_ml_pipeline, task_id=setup_mlflow, run_id=manual__2025-06-11T12:13:31.335012+00:00, execution_date=20250611T121331, start_date=20250611T121334, end_date=20250611T121334
[2025-06-11T12:13:34.975+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-11T12:13:35.013+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-11T12:13:35.015+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
